[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aiopapouch"
version = "0.1.4"
description = "API client and device models for Papouch's devices"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "VladislavLevitskii", email = "vladlevitskii@gmail.com" }
]
dependencies = [
    "aiohttp>=3.0.0",
    "defusedxml>=0.7.1"
]

[project.urls]
Source = "https://github.com/VladislavLevitskii/aiopapouch"

[tool.hatch.build.targets.wheel]
packages = ["src/aiopapouch"]
